/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function is_point_2_on_circle_segment_2(a: number, b: number): number;
export function locate_point_2_circle_segment_2(a: number, b: number): number;
export function is_point_2_on_line_segment_2(a: number, b: number): number;
export function locate_point_2_line_segment_2(a: number, b: number): number;
export function point_2_project_line_segment_2(a: number, b: number): number;
export function __wbg_triangle2indices_free(a: number): void;
export function __wbg_get_triangle2indices_a(a: number): number;
export function __wbg_set_triangle2indices_a(a: number, b: number): void;
export function __wbg_get_triangle2indices_b(a: number): number;
export function __wbg_set_triangle2indices_b(a: number, b: number): void;
export function __wbg_get_triangle2indices_c(a: number): number;
export function __wbg_set_triangle2indices_c(a: number, b: number): void;
export function earcut(a: number, b: number): void;
export function __wbg_linesegment2_free(a: number): void;
export function linesegment2_new(a: number, b: number): number;
export function linesegment2_segment_type(a: number): number;
export function linesegment2_source(a: number): number;
export function linesegment2_target(a: number): number;
export function __wbg_convexhull2_free(a: number): void;
export function convexhull2_new(a: number, b: number): number;
export function convexhull2_convex_hull(a: number, b: number): void;
export function __wbg_sweepsegment2intersection_free(a: number): void;
export function sweepsegment2intersection_new(): number;
export function sweepsegment2intersection_push_segment(a: number, b: number): void;
export function sweepsegment2intersection_intersection(a: number, b: number): void;
export function is_point_2_on_arc_segment_2(a: number, b: number): number;
export function locate_point_2_arc_segment_2(a: number, b: number): number;
export function locate_point_2_polygon_2(a: number, b: number): number;
export function locate_point_2_triangle_2(a: number, b: number): number;
export function __wbg_arcsegment2_free(a: number): void;
export function arcsegment2_new(a: number, b: number, c: number): number;
export function arcsegment2_segment_type(a: number): number;
export function arcsegment2_source(a: number): number;
export function arcsegment2_source_radian(a: number): number;
export function arcsegment2_target(a: number): number;
export function arcsegment2_target_radian(a: number): number;
export function arcsegment2_center(a: number): number;
export function arcsegment2_radius(a: number): number;
export function __wbg_point2_free(a: number): void;
export function point2_new(a: number, b: number): number;
export function point2_x(a: number): number;
export function point2_y(a: number): number;
export function point2_equals(a: number, b: number): number;
export function point2_get_vector(a: number): number;
export function point2_distance(a: number, b: number): number;
export function point2_turn(a: number, b: number, c: number): number;
export function __wbg_polygon2_free(a: number): void;
export function polygon2_new(a: number, b: number): number;
export function polygon2_vertices(a: number, b: number): void;
export function polygon2_edges(a: number, b: number): void;
export function polygon2_area(a: number): number;
export function polygon2_is_simple(a: number): number;
export function polygon2_is_convex(a: number): number;
export function __wbg_circlesegment2_free(a: number): void;
export function circlesegment2_new(a: number, b: number): number;
export function circlesegment2_segment_type(a: number): number;
export function circlesegment2_center(a: number): number;
export function circlesegment2_radius(a: number): number;
export function __wbg_segment2_free(a: number): void;
export function __wbg_get_segment2_segment_type(a: number): number;
export function __wbg_set_segment2_segment_type(a: number, b: number): void;
export function __wbg_get_segment2_line_segment_2(a: number): number;
export function __wbg_set_segment2_line_segment_2(a: number, b: number): void;
export function __wbg_get_segment2_circle_segment_2(a: number): number;
export function __wbg_set_segment2_circle_segment_2(a: number, b: number): void;
export function __wbg_get_segment2_arc_segment_2(a: number): number;
export function __wbg_set_segment2_arc_segment_2(a: number, b: number): void;
export function segment2_new(a: number, b: number, c: number, d: number): number;
export function __wbg_triangle2_free(a: number): void;
export function triangle2_new(a: number, b: number, c: number): number;
export function triangle2_b(a: number): number;
export function triangle2_c(a: number): number;
export function triangle2_vertices(a: number, b: number): void;
export function triangle2_edges(a: number, b: number): void;
export function triangle2_orientation(a: number): number;
export function triangle2_reverse_orientation(a: number): void;
export function triangle2_area(a: number): number;
export function __wbg_vector2_free(a: number): void;
export function vector2_new(a: number, b: number): number;
export function vector2_x(a: number): number;
export function vector2_y(a: number): number;
export function vector2_length(a: number): number;
export function vector2_normalize(a: number): number;
export function vector2_dot(a: number, b: number): number;
export function vector2_cross(a: number, b: number): number;
export function vector2_radian_to(a: number, b: number): number;
export function triangle2_a(a: number): number;
export function is_segment_2_segment_2_intersected(a: number, b: number): number;
export function segment_2_segment_2_intersection(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
